Aula06/06_Poo/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using PooModel;
using Repository;

namespace _06_Poo.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private CustomerRepository? _customerRepository;

        public CustomerController(IWebHostEnvironment environment)
        {
            _customerRepository = new CustomerRepository();
            _environment = environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Customer> customers = _customerRepository!.RetriveAll();

            return View(customers);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer c)
        {
            _customerRepository!.Save(c);

            List<Customer> customers = _customerRepository!.RetriveAll();

            return View("Index", customers);
        }

        [HttpGet]
        // Por padrao ele pega a view com o mesmo nome do metodo
        public IActionResult ExportDelimitatedCustumer()
        {
            string fileContent = string.Empty;
            foreach (Customer c in CustomerData.Customers)
            {
                foreach (Address address in c.AddressList!)
                {
                    fileContent += $"{c.Id};{c.Name};{address.id};{address.City};{address.State};{address.Country};{address.StreetLine1};{address.StreetLine2};{address.PostalCode};{address.AddressType};\n";
                }

            }

            var path = Path.Combine(
                _environment.WebRootPath,
                "TextFiles/Customer"
            );

            if(!System.IO.Directory.Exists( path ) )
                System.IO.Directory.CreateDirectory( path );

            var filepath = Path.Combine(
                path,
                "DelimitatedCustomer.txt"
            );

            if(!System.IO.File.Exists( filepath ) )
            {
                using (StreamWriter sw = System.IO.File.CreateText( filepath ) )
                {
                    sw.Write(fileContent);
                }
            }

            return View("Export");
        }
    }
}

Aula06/06_Poo/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Repository;
using PooModel;

namespace _06_Poo.Controllers
{
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private ProductRepository? _ProductRepository;

        public ProductController(IWebHostEnvironment environment)
        {
            _ProductRepository = new ProductRepository();
            _environment = environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Product> Products = _ProductRepository!.RetriveAll();

            return View(Products);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product c)
        {
            _ProductRepository!.Save(c);

            List<Product> Products = _ProductRepository!.RetriveAll();

            return View("Index", Products);
        }

        [HttpGet]
        public IActionResult ExportDelimitatedProduct()
        {
            string fileContent = string.Empty;
            foreach (Product p in ProductData.Products)
            {
                fileContent += $"{p.Id};{p.Name};{p.Description};{p.CurrentPrice}\n";
            }

            var path = Path.Combine(
                _environment.WebRootPath,
                "TextFiles/Product"
            );

            if (!System.IO.Directory.Exists(path))
                System.IO.Directory.CreateDirectory(path);

            var filepath = Path.Combine(
                path,
                "DelimitatedProduct.txt"
            );

            if (!System.IO.File.Exists(filepath))
            {
                using (StreamWriter sw = System.IO.File.CreateText(filepath))
                {
                    sw.Write(fileContent);
                }
            }

            return View("Export");
        }
    }
}

Aula06/06_Poo/Views/Customer/Index.cshtml
@model List<PooModel.Customer>

@{
    ViewData["Title"] = "Customer List";
}

<div class="text-center mb-4">
    <h1 class="display-5">Customer List</h1>
</div>
<hr>

<div class="mb-3">
    <a asp-action="Create" asp-controller="Customer" class="btn btn-light">
        New Customer
    </a>
</div>

@if (Model != null && Model.Count > 0)
{
    <table class="table table-striped table-hover">
        <thead class="thead-light">
            <tr>
                <th>Id</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>@customer.Id</td>
                    <td>@customer.Name</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning">
        There are no customer records.
    </div>
}

<div class="mb-3">
    <a asp-action="ExportDelimitatedCustumer" asp-controller="Customer" class="btn btn-primary">
        Export to txt File
    </a>
</div>

Aula06/06_Poo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _06_Poo</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_06_Poo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025  -   <a href="https://github.com/KalilMassignaniDaRosa/Programming-25">Kalil M. da Rosa</a>  -  
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>